

on:
  push:
    tags:
      - "v*"

jobs:
  docker-registry:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Build and push authService microservice
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./src/authService
          file: ./src/authService/Dockerfile
          tags: wafaselmi/authservice:${{ steps.get_version.outputs.VERSION }}
      - name: Build and push converterService microservice
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./src/converterService
          file: ./src/converterService/Dockerfile
          tags: wafaselmi/converterservice:${{ steps.get_version.outputs.VERSION }}
      - name: Build and push gatewayService microservice
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./src/gateway
          file: ./src/gateway/Dockerfile
          tags: wafaselmi/gatewayservice:${{ steps.get_version.outputs.VERSION }}    